name: Linting & Testing

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - "release/**"
    paths:
      - "**.json"
      - "**.php"
      - "**.yml"
  pull_request:
    branches:
      - master
      - "release/**"
    paths:
      - "**.json"
      - "**.php"
      - "**.yml"

jobs:
  laravel-pint:
    name: PHP Linting (Pint)

    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # Make sure the actual branch is checked out when running on pull requests.
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Laravel Pint
        uses: aglipanci/laravel-pint-action@2.4

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true

  testing:
    needs: laravel-pint

    strategy:
      fail-fast: true
      matrix:
        php: [8.4, 8.3, 8.2]
        testbench: [10.0, 9.0, 8.0] # Laravel 12.x, 11.x, 10.x
        version: [prefer-stable, prefer-lowest]

    name: P${{ matrix.php }} - T${{ matrix.testbench }} - ${{ matrix.version }}

    runs-on: ubuntu-latest

    container:
      image: kirschbaumdevelopment/laravel-test-runner:${{ matrix.php }}
      options: "--user=root"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # Make sure the actual branch is checked out when running on pull requests.
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          composer require --dev "orchestra/testbench:^${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest --parallel
